### PR TITLE
Version bumped to 0.2.0.

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by marinang** [comment]
@eduardo-rodrigues I just found a tiny mistake in Selection. Possible to put to fix it before the release?

**Comment by eduardo-rodrigues** [comment]
Sure. Just add the fix to this PR?

**Comment by marinang** [comment]
@eduardo-rodrigues I'll do asap.

**Comment by marinang** [comment]
All good on my side ;)

**Pull request merged**
