### PR TITLE
Fix issue in selection, coming from pyparsing >=  2.2.2

### PR DESCRIPTION
**Pull request by marinang**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Wow, not at all a trivial fix in the end.

**Comment by marinang** [comment]
Wait before merging I am just adding one requirement.

**Comment by eduardo-rodrigues** [comment]
To make the link: this PR fixes an issue raised in https://github.com/scikit-hep/scikit-hep/pull/76.

**Comment by marinang** [comment]
@eduardo-rodrigues  I have added all what I wanted to add.

**Comment by eduardo-rodrigues** [comment]
I will go ahead and merge - technically I trust you on this :-).

Many thanks for such a speedy fix!

**Pull request merged**
