### PR TITLE
ci: Add workflow to test current releases from PyPI

### LINKED ISSUE #108: Docker container to be able to test compatibility of all packages?
Following up from the quick chat on Gitter - @matthewfeickert, would it make sense to try and have an environment test in a container to make sure that whatever dependencies we set/update for this (eventually to become) metapackage we are consistent? Maybe there's a simpler way to achieve this and I'm just being naive?

Cc @henryiii as well.

Thanks.

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves #108 

```
* Add unbounded dependency list
* Add workflow to run tests using the latest releases on PyPI
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@eduardo-rodrigues I'm just throwing this up here to get things started, but beyond maybe some small cleaning I think this should already accomplish the goal of Issue #108. Thoughts?

**Comment by eduardo-rodrigues** [comment]
Yes @matthewfeickert this seems very good to me. Beyond that one would do some mini notebook with some manipulations, but that's probably over the top. So good to go. Many thanks!

**Comment by matthewfeickert** [comment]
> mini notebook with some manipulations

As in a notebook that would run through examples from each library? That could be added to the test suite using [`papermill`](https://papermill.readthedocs.io/en/latest/).

**Comment by eduardo-rodrigues** [comment]
Yep, probably - though I never actually implemented something with `papermill`.

Note that in `Particle` we do test the notebook demo without `papermill`, see https://github.com/scikit-hep/particle/blob/master/.github/workflows/ci.yml.

I'm removing the Draft status. Please merge if happy as well. Thank you.

**Comment by matthewfeickert** [comment]
> I'm removing the Draft status. Please merge if happy as well. Thank you.

Sounds good. I was going to think if there was something more "clever" that we could do so that instead of having to duplicate the `requirements.txt` into `requirements_current_release.txt` we could parse out only the package names. However, this probably isn't worth it _right now_ and we can fix it in the future if it is annoying.

**Pull request merged**
