### PR TITLE
Copied the hep_ipython_tools from their own project 

### PR DESCRIPTION
**Pull request by nils-braun**
I also adjusted some code to make it fit. 
Also added the tests.

This is a rather large PR, because it dumps the whole project in it - but lets see this as a starting point.

I can give more information on the python files and also include more documentation - but I only want to do this if we conclude to keep this in the code base.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Nils, nice to see this coming in so quickly after we chatted!
I cannot do any proper reading of this large PR at this stage (will do asap) but for now I would only comment that one could simplify the module name; maybe to something like skhep/utils/ipythonutils.py or ipythontools.py?

**Comment by eduardo-rodrigues** [comment]
Oh, and could you maybe add a doctoring at the top of the module with some info on what it brings/provides? Something along the idea in skhep/math/vectors.py for example.

**Comment by eduardo-rodrigues** [comment]
Nils, getting back to this! Sincere apologies.
I'm wondering indeed whether it would be better to have this big module as an affiliated package, so under https://github.com/scikit-hep? How much of your code is HEP-specific'ish and how much could be put into a more official ipython-related package?

**Comment by nils-braun** [comment]
Sorry, for my late answer. I think most of it can live in its own project. I will think about what exactly and come back with a new solution - this may take some time however

**Comment by eduardo-rodrigues** [comment]
OK, sounds good. I'm very happy to chat BTW ...

**Comment by nils-braun** [comment]
I have thought about it.
So actually, nothing is really HEP specific. I mean, if you have something like "modules" that are processed one after the other in some sort of "module path", you are fine with my package.
This is especially true for all HEP frameworks I am aware of - but this can also be true in other projects (apart from HEP). So do you want to create a new affiliated project?

**Comment by eduardo-rodrigues** [comment]
That's probably best, yes. Then you could add some common examples of usage, etc.
Opinions from anyone else? Otherwise I would say go ahead tomorrow if you hear nothing else :-).

**Comment by eduardo-rodrigues** [comment]
On the way, could you try and fix things for Python 2.7?

**Comment by eduardo-rodrigues** [comment]
Hi @nils-braun, it's been a very long time since you last commented on this package. Could you share your present thoughts? Thanks.

**Comment by nils-braun** [comment]
Hi @eduardo-rodrigues. Unfortunately, my PhD thesis eats up all of my time now and I need to take care of those things first.
I am very sorry that I could not work on this project for so long and unfortunately, I think this may still need some more time until I can do something....
I am still willing to do something here, but I do not think this is very time critical. Please apologize for me not working on this :-(

**Comment by eduardo-rodrigues** [comment]
Ah, that's an **excellent** reason to pause on other matters! Good luck with finishing (successfully) your PhD :-)! I look forward to hearing back from you ... in due time ...

**Comment by eduardo-rodrigues** [comment]
@nils-braun, shall I go ahead and close this at this point in time? Seems reasonable, even more given that this package will become in the medium term a metapackage.

**Comment by nils-braun** [comment]
Yes, you can close it.

**Comment by eduardo-rodrigues** [comment]
Thanks for the confirmation, @nils-braun. Hope all is good with you and I look forward to your contributions to Scikit-HEP packages.

**Pull request closed without merging**
