### PR TITLE
DRAFT: Prepare release 2024.10.1

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
**Packages updated (minor version updates):**
- histoprint
- iminuit
- uproot

**Full set of packages and pinned versions:**
```
awkward~=2.6.0
decaylanguage~=0.18.0
hepstats~=0.8.0
hepunits~=2.3.0
hist~=2.8.0
histoprint~=2.5.0
iminuit~=2.30.0
mplhep~=0.3.0
particle~=0.25.0
pylhe~=0.9.0
resample~=1.10.0
uproot~=5.4.0
vector~=1.5.0
```

**Miscellaneous:**
- Added support for Python 3.13.
- Formatting with Ruff.
- Configuration modernised.
- Updates to the pre-commit hooks and GitHub actions.

### CODE REVIEW

**Comment by jonas-eschle** [comment]
hepstats is now Python 3.13 compatible as well! zfit is still lacking, as some deps are missing, but hepstats has zfit as an optional dependency

**Comment by eduardo-rodrigues** [comment]
Thanks a lot, @jonas-eschle. I am traveling and then away all of this week. I will try and act unless somebody from the team closes this PR and makes a 2024.11.1 release.

**Comment by jonas-eschle** [comment]
@eduardo-rodrigues published the new release: https://github.com/scikit-hep/scikit-hep/releases and succesfully deployed to PyPI

**Comment by eduardo-rodrigues** [comment]
Thanks a lot @jonas-eschle!

**Pull request merged**
