### PR TITLE
[FIXME] Take IDs directly by name directly from PDT

### PR DESCRIPTION
**Pull request by ab-10**
Create a dictionary that maps names of particles within the range neccessary used in test to their IDs and set particle test variables equal to their respective entries in dictionary. Done because of the FIXME.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi, Thanks for being interested in the project! I tried to find you in the list of stargazers but did not find you. How did you come to the project and got interested? Are you a particle physicist?
There are a couple of problems with your PR:
- It's failing.
- One should not at all import dependencies in a test of skhep. We are testing skhep after all. I realise there are missing bits I want to add to code related to PyPDT, but that is not a reason to break such a normal rule.
Would you like to contribute further to the project? Do you have ideas or fancy discussing ideas? You can drop me a line by email.
Thanks.

**Comment by ab-10** [comment]
Hi, I found out about this project as part of Google Summer of Code. I would like to work on integrating Vega interface into this library. I am interested in this project, since I would like to learn more about data analysis, but I don't have any particle physics background.

Regarding PR issues:

- The reason why I submitted a failing PR, is because the original also failed on my system, is that not the case on your machine?

- I understood the FIXME as a request for direct access to skhep for the particle IDs, did I misunderstand the task?

**Comment by eduardo-rodrigues** [comment]
Very briefly for now: did you then get in touch with Jim and David? The start date for GSoC student proposals was this Monday and as far as I know you did not yet get in touch?
As one can see from the GitHub pages the tests ran just fine on Travis and locally, yes. Strange they did not for you.
The FIXME is there so that we do not forget one can do better than what is in there at the moment. Like I said, there are missing bits in module simulation.pdg, which will come soon.

**Comment by davidlange6** [comment]
> On Mar 24, 2017, at 2:33 PM, Eduardo Rodrigues <notifications@github.com> wrote:
> 
> Very briefly for now: did you then get in touch with Jim and David? The start date for GSoC student proposals was this Monday and as far as I know you did not yet get in touch?

to answer the easy part, yes, we are in touch.

**Comment by eduardo-rodrigues** [comment]
OK, just was not aware. Great. Keep us all posted ... ;-)

**Comment by ab-10** [comment]
I guess I just misunderstood the FIXME comment then. I've already submitted a different PR for histogrammar as my demonstrative ([print of ascii histogram](https://github.com/histogrammar/histogrammar-python/pull/22)). What was the reason why you reopened this PR?

**Comment by eduardo-rodrigues** [comment]
I did not want to close it and clicked the wrong button by mistake ;-). Now that you committed this update I can work out the changed I wanted and merge ... rather than doing part of the same thing again ... I'll see what's easiest anyway.

**Comment by eduardo-rodrigues** [comment]
Closing this since the work will be done in a different way.

**Pull request closed without merging**
