### PR TITLE
Particle, boost-histogram, hepunits, iminuit dependencies update, add Hist, mplhep

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
@henryiii, you had asked to wait for BH 0.11 to make a first scikit-hep metapackage release. This seems to be the last step required for the (long due) release. Anything else you would like in? We can be fancier in the future but I think it really is about time that we get this out. We should then get scikit-hep on conda, as that's where it will be even more useful ...

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Mea culpa - of course I need to update the dependency of `DecayLanguage` accordingly ... Let me release a new version of it ...

**Comment by eduardo-rodrigues** [comment]
BTW, in the meantime I started updating `hepunits`, and will soon tag the update as a major release. I will include that here as well.

**Comment by henryiii** [comment]
Let's add `hist~=2.0.0` as well.

**Comment by henryiii** [comment]
PS: to add something on conda, you need all the dependencies also on conda. That means we need a few releases on conda (at least hist).

**Comment by eduardo-rodrigues** [comment]
Sure. To be clear, just plain `Hist` withouth the `[plot]` option. I think for a first version we should not try and include the whole thing, to iterate and make sure we have a robust installation.

**Comment by eduardo-rodrigues** [comment]
Wait, but `Hist` is only Python 3 whereas we had agreed to start with a `scikit-hep` metapackage release that would be compliant with Python 2.7.

**Comment by eduardo-rodrigues** [comment]
> PS: to add something on conda, you need all the dependencies also on conda. That means we need a few releases on conda (at least hist).

That's understood.  Having this package in conda does impose a few things, and a bit more work.

**Comment by chrisburr** [comment]
It it worth the effort of deploying for Python 2 given the current state of things? Anyone who really needs it can always install the dependencies individually.

**Comment by henryiii** [comment]
I would include `mplhep`, which is exactly that the `[plot]` option does anyway.

You can use environment markers to keep these dependencies out of Python 2 (as mplhep, pyhf at least are Python 3 only as well).

```
hist~=2.0.0; python_verison>="3.6"
mplhelp~=0.2.2; python_verison>="3.6"
```

should do it.

**Comment by eduardo-rodrigues** [comment]
It's not *that* worth it, you're right. On the other hand there's little effort in releasing for Python 2 since the release for Python 3 will be a superset ... My main point is that we said we would do it, and some (hopefully not many) may still find the release useful, hence the little motivation.

**Comment by henryiii** [comment]
Actually, iminuit 1.4.0 doesn't support Python 2, so it should already be broken under Python 2 with the current list. You can do:

```
iminuit~=1.3.0; python_verison<"3.6"
iminuit~=1.5.0; python_verison>="3.6"
```

if you want to fix it.

**Comment by henryiii** [comment]
(I wouldn't bother to do a python 2 + conda version, though)

**Comment by eduardo-rodrigues** [comment]
Interesting @henryiii, I thought that CI test we discussed with @matthewfeickert was precisely to try and catch inconsistencies. So something isn't working the way it was meant to ... :S

**Comment by eduardo-rodrigues** [comment]
> (I wouldn't bother to do a python 2 + conda version, though)

Agreed.

**Comment by henryiii** [comment]
The tests logs a) clearly show iminuit failing and b) pass with flying colors.

**Comment by eduardo-rodrigues** [comment]
"a)" and "b)"? I don't understand your sentence. Let me see those logs ...

**Comment by eduardo-rodrigues** [comment]
Sorry, where do you see the failures? If I click on the CI button in the README I see it all green - https://github.com/scikit-hep/scikit-hep/actions?query=workflow%3ACI+branch%3Amaster.

**Comment by henryiii** [comment]
The tests claim to pass (point b). But if you look in the logs for Python 2, you can see it actually tries to build iMinuit (since no wheel is available), and fails. iMinuit is missing `python_requires`, so the error message is not nearly as good as it should be (and it should "just-work" if you ask for `python2 -m pip install iminuit` if it had set a `python_requires`).

**Comment by eduardo-rodrigues** [comment]
OK, I will commit as per our discussions later today. I will also include a new major release of `hepunits` - I left a PR for you to review, just in case.

**Comment by eduardo-rodrigues** [comment]
OK folks, this does not contain *all* of Scikit-HEP but it could be enough a set for a first metapackage release.

**Comment by eduardo-rodrigues** [comment]
I just tried locally on my Windows laptop with Docker and things are looking good:

```
root@7f91c91e8871:/scikit-hep# python
Python 3.8.6 (default, Sep 24 2020, 21:45:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import skhep
>>> skhep.show_versions()

System:
    python: 3.8.6 (default, Sep 24 2020, 21:45:12)  [GCC 8.3.0]
executable: /usr/local/bin/python
   machine: Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.2.5

Python dependencies:
       pip: 20.2.3
setuptools: 50.3.0
     numpy: 1.19.2
     scipy: 1.5.2
    pandas: 1.1.2
matplotlib: 3.3.2

Scikit-HEP package dependencies:
        awkward: 0.13.0
boost_histogram: 0.11.0
  decaylanguage: 0.8.0
       hepunits: 2.0.0
           hist: 2.0.0
        iminuit: 1.5.2
         mplhep: 0.2.2
       particle: 0.12.0
 uproot_methods: 0.7.4
         uproot: 3.12.0
```

This is ready IMO.

**Review by henryiii — APPROVED** [review]

**Pull request merged**
