### PR TITLE
Creation of vectors module with first draft of a 3D vector class.

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
This module is to contain the Vector3D and LorentzVector classes. Both independent of ROOT.
Note: the testing module is yet to be written. Just a few lines exist for now.

It is important to discuss the API at this stage.

### CODE REVIEW

**Comment by davidlange6** [comment]
Hi @eduardo-rodrigues - did you evaluate the pro/con of basing this on numpy.ndarray? [looking around, I'm a bit surprised not to find "standard" implementations of Lorentz vectors out there, but google doesn't suggest much information on this topic ]

**Comment by eduardo-rodrigues** [comment]
Hi David, thanks for having a look.

I also looked around and was very surprised not to find such basic classes in Python. To be fair I actually found some examples and partially implemented solutions, typically in a module with just the class. I found issues with the robustness of the implémentations, and missing bits. Rather than taking a long time to try and get that up to our needs, getting in touch with the authors, etc., I decided to implement it myself. It's actually must more efficient in this instance.

I did think about alternatives such as an array or ndarray. I'm not sure at all what advantages these would have. In general I go with the simplest solution and in the end we just want to store 3 numbers. Are there performance and/or memory penalties with the present implementation? Not sure.
The other reason for the present code is that I reckon we have to move forward with the design of the API and that can be done now. If we feel the storage should rather be an ndarray later on, the API will hardly change, if at all.
All in all this explains it.

**Comment by VanyaBelyaev** [comment]
a bit provocative question - do we really need to be ROOT independent?
ROOT point/vector/lorentz-vector machinery  (I am talking about ROOT::Math::XXX and not about TXX) is rather nice, and python layer needed to make it even nicer in python is very light (can b
e copied from ostap).

**Comment by eduardo-rodrigues** [comment]
Vanya, no worries ;-). I was sure this question would come ...
The very fact that one cannot find in HEP (or largely elsewhere, really) a proper python-only implementation of such basic objects sounded like a call in my ears. I use ROOT a lot, as you know, but am sure I will be using it less in the near future and, more importantly, see that the younger generations use ROOT much much less, rather relying on the alternative tools there is no need to re-list here. So yes, I do reckon we ought to provide these classes for anyone working without ROOT (regarless of (s)he having it installed). My 2 cents :-).

**Comment by davidlange6** [comment]
hi @eduardo-rodrigues - the advantages to me of ndarray is that most of the functionality you have is already there and becomes a trivial implementation in your class. Indeed, can be considered later as is not likely change in API (though maybe the API should be checked to be consistent).

eg,
http://ilan.schnell-web.net/prog/vec3/vec3.txt
is one example I found (well, really the only one)

and this discussion was informative 
http://stackoverflow.com/questions/19458291/efficient-vector-point-class-in-python

**Comment by eduardo-rodrigues** [comment]
Thanks for the pointers, David. Will have a look.
Right, little API changes at such an early stage - we have not even released a version 0.1 - are no problem. There cannot be too many, in any case.

**Pull request merged**
