### PR TITLE
Introduction of MultiProvenance. Modification of NumpyDataset. Introduction of Selection Framework.

### PR DESCRIPTION
**Pull request by marinang**
Hi. 

Following issue #54. I created a class MultiProvenance which is basically a container of Provenances. Every dataset should have one MultiProvenance instance which collects history of Origin/....Transformations.
The representation of a MultiProvenance is as follow:

`MP = MultiProvenance(ObjectOrigin("origin"))`
`MP += Transformation("transformation")`
`MP += Formatting("format")`
`print MP:`

`0: <ObjectOrigin>`
`1: <Transformation(transformation)>`
`2: <Formatting to format>`

Then one can access to a given provenance like this:

`print MP[1]`: <Transformation(transformation)>
`print MP[0].detail`: origin
...

From this I decided to go ahead and implement this and other stuffs in NumpyDataset.
So for example if we have:
`ar = np.array([(1,1),(2,2),(3,3)],dtype=[('x',int), ('y',int)])
ds = NumpyDataset(ar)`

`print ds.provenance`: 0: <ObjectOrigin

I thought that it would be very convenient to put the observables/variables as property attributes of the instance of NumpyDataset. Like this`print ds1.x`: [1 2 3] and also `print ds1['x']`: [1 2 3].

What I think is awesome for an analysis point of view is to add variables in the dataset as easy as possible. What is possible to do here is for instance `ds1.z = np.zeros((3,))` (equivalently `ds1["z"] = np.zeros(ds.shape)`) or even something like this `ds1.r = (ds1.x**2 + ds1.y**2)**0.5`.
Now if you check the provenance you have:

`print ds.provenance[-1]`: <Transformation(Array z has been created)>

I've also implemented a way to add history of operations on variables/observables of the dataset. The way I found to do that is to create a np.ndarray subclass called "SkhepNumpyArray" which has name and provenance (MultiProvenance) attributes. I've overriden `__array_ufunc__` to add any transformation to the provenance attribute. The information from provenance of the variable are then brought back to the dataset. An example:

`print repr(ds.x)`: SkhepNumpyArray([1, 2, 3])
`print ds.x.name`: x
`print ds.x.provenance`: 0: <ObjectOrigin>
`print ds.x.provenance[0].detail `: NumpyDataset([(1, 1), (2, 2), (3, 3)],\n      dtype=[('x', '<i8'), ('y', '<i8')])

`ds.x += 1`
`print ds.provenance[-1]`: <Transformation(1 as been added to x)>
`ds.y /= 2`
`print ds.provenance[-1]`: <Transformation(y as been divided by 2)>

Other things you can do:
`a = ds.x + ds.y; print a.name`: x + y
`b = ds.x > ds.y; print a.name`: x > y

I guess I've shown the spirit of it. What do you think?

I went further introducing a Selection framework in order to give for example selection "à la ROOT" to NumpyDataset.
`from .dataset.selection import Selection`
`ds = NumpyDataset(ar)`
`sel = Selection("x > 1")`
`ds1 = ds.select(sel)`
`print ds1.provenance[-1]`:  <Transformation(Selection, (x > 1), applied)>

`print repr(ds1)`: "NumpyDataset([(2, 2), (3, 3)],\n      dtype=[('x', '<i8'), ('y', '<i8')])"
 
It is possible to combine selection with '|' or '&':
`sel1 = Selection("x > 1")`
` sel2 = Selection("y < 2")`
`print sel1 | sel2`: x > 1 | y < 2
`print sel1 & sel2`: x > 1 & y < 2

I've learned how to use pyparsing and to parse the input string of `Selection` and you can give selection like this: `sel = Selection( "(max( x, y ) > 1) | (x + y)^2  <=  2)" )`
I've checked this is working, but I've might have missed some cases...

Happy new year. Matt

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi @marinang, Happy New Year to you too!
Great to see this! It's a mega PR so am adding various people for the review. @alexpearce and @chrisburr are added in particular for what concerns possible links between your Selection additions and analysis work they've done in Python, and root_pandas/numpy functionality.

**Comment by marinang** [comment]
https://github.com/scikit-hep/scikit-hep/pull/57/commits/e6649f1f65af3e5e1d377cfc84cdb86a309c50f7 Well I've attended to solve fix build failures for python 2.6 and python 3.4, but didn't succeed 😅, the problems are the same for both. 

Concerning the Selection framework. I tried to make it very independent of the type of dataset. There is a method called `evaluateselection` which takes as inputs the dataset (should have `__getitem__`), operators, and min and max functions... For example a selection has property called numpyselection which calls `evaluateselection`.

**Comment by eduardo-rodrigues** [comment]
Finally getting back to this! Thanks again for all the work. I started reviewing things ...
I very much like the way you prepared the provenance-like classes. I'm in general happy there and will point out little things that I may be misunderstanding or that I do not quite like.
It's a shame, in some sense, that you did not split the addition of MultiProvenance + improvements/enhancements to the provenance-like classes from the rest of the updates. It's a lot to take.

**Comment by marinang** [comment]
@eduardo-rodrigues Yes sorry about that, for future developments I will be more careful regarding splitting them in different PR.

**Comment by eduardo-rodrigues** [comment]
Can you dwell a bit more on SkhepNumpyArray? Is this just meant to be internal, meaning the user would not have to instantiate it and all that? Or ...?

**Comment by marinang** [comment]
It is meant to be internal. It is just a normal numpy.ndarray modified in order to take care provenances and when you want to get a special variable from your NumpyDataset it is returned as SkhepNumpyArray (actually of copy for mutability reasons).
I introduced it because I didn’t find another way to modify a variable from a NumpyDataset with some operations and modify in the same time the provenance of the same dataset except by overloading the operators of numpy.ndarray...

**Comment by eduardo-rodrigues** [comment]
OK, thanks.
Moving forward, will you have time to deal with the other interleaved comments in the next few days?
Then remains the issue with compilation on Python 2.6 and 3.4. This touches a wider discussion we should have on supported versions. For example, root_pandas does not (at least) explicitly support 2.6.
Any other feedback @chrisburr and @alexpearce ?

**Comment by marinang** [comment]
@eduardo-rodrigues Yes I will have time.
About compilations issues I think addition of __add__, __mul__ ... calling __array__ufunc__ might solve this.

**Comment by eduardo-rodrigues** [comment]
Thanks. Looking forward to the updates :-)! It would be great to be able to merge this to master in the near future.

**Comment by marinang** [comment]
@eduardo-rodrigues the python 2.6 build failed but I'm afraid it is not because of me. Right time to think about throwing it away x).

Anyway any other feedback?

**Comment by eduardo-rodrigues** [comment]
Re:build for py2.6: yes. Strange though that this is new. Will look later ...
Thanks a lot for the updates! But did you reply to the 3 questions on particular lines of code, such as "Did you not implement the `detail` property?"? I will now look at the updates ...
Note that @chrisburr promised to look into this PR over the next few days so let's keep it open just a bit longer.

**Comment by marinang** [comment]
@eduardo-rodrigues Actually I do not see any comments in the code.

**Comment by eduardo-rodrigues** [comment]
Ah, for me they appear on this page above, in the discussions, and also inhttps://github.com/scikit-hep/scikit-hep/pull/57/files.
Basically:

- Did you not implement the `detail` property in the MultiProvenance class?

- Code such as `assert ds.provenance[0].__repr__() == '<ObjectOrigin>'` in test_numpydataset.py: I said this way of looking at provenance info may seem ugly at first. What does ds.provenance provide? If the MultiProvenance object contains a single one then the printout should be just as for a simpler class as ObjectOrigin I would say. Of course the above is fine in the sense that one should be able to check all "items" in the MultiProvenance object.

- In same file test_numpydataset.py: can you also add an assert for `ds2.provenance.__repr__()` ?

**Comment by marinang** [comment]
@eduardo-rodrigues Thanks! It is strange they do not appear at all for me.

**Comment by eduardo-rodrigues** [comment]
Yep. I was indeed wondering why you had not responded to those comments in spite of the fact that you are always comprehensive and clear ;-).

**Comment by eduardo-rodrigues** [comment]
@chrisburr, you mentioned you were going to have a look. Can I proceed and accept this MR?
We agreed anyway that we should probably revise certain aspects, making use of the new `formulate` package. That's beyond this MR, though.
Thanks.

**Comment by marinang** [comment]
@eduardo-rodrigues It depends what was the point of those methods? I thought It was introduced to implement like mathematic operations but since the NumpyDataset is like a modified record array this cannot work (Tell me If I'm wrong).

**Comment by eduardo-rodrigues** [comment]
That was the purpose, yes, since the array was simply stored as is in the class, which contains more info such as provenance info.
Not sure either. I would have to check. But was indeed under the impression that one could still define those methods on the stored data object ... OK, to move forward, can you just comment out those lines removed for addNumpyMethod, instead of removing them, and we merge this all? Thanks.

**Pull request merged**
