### PR TITLE
Additions/Modifications on vectors.py

### PR DESCRIPTION
**Pull request by marinang**
Hi,
I've added modifications to the vector3D class and completed some method. I've also added rotations.
The most of the work was on LorentzVector, which is now rather complete. I've added different setter, rotations, boost... One thing that can be still missing is a general Lorentz Transformation.
Everything is tested!
Matt

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi Matt, thanks a lot for taking care of this according to what we discussed!
As you can see, Vanya worked further on the vectors module and there are little conflicts to resolve. Can you take care of that? Shouldn't bee too difficult.

**Comment by marinang** [comment]
Hi Eduardo, I've solved few conflicts, but they are still remaining conflicts about new methods that I introduced.

**Comment by eduardo-rodrigues** [comment]
Strange, conflicts can not happen with new code. Will have a look ...

**Comment by eduardo-rodrigues** [comment]
OK I reckon I solved the conflicts. Let's see ...

**Comment by marinang** [comment]
Ok and I see that you solved the indentation with LorentzVector.copy(), For the conflicts, did I miss something, why were my new pieces of code in conflicts?

**Comment by eduardo-rodrigues** [comment]
@VanyaBelyaev, do you also want to comment on the additions from Matt?

**Comment by marinang** [comment]
I'm rerunning my tests locally within this branch, but the __sub__ method for vectors seems not to be called anymore. For example if I do 
`v1, v2 = Vector3D(2., 2., 2.), Vector3D(3., 3., 3.)
print v1 - v2`
it gives
Vector3D(5., 5., 5.).

**Comment by eduardo-rodrigues** [comment]
Thanks again for the work! There are a few little things to fine-tune but nothing that prevents this large PR from being merged.

**Pull request merged**
