### PR TITLE
Add hepstats, replace skhep.modeling with hepstats.modeling

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
FYI and review @marinang. I'm making the replacement of the import statements to check things are OK before removing the submodule `modeling` and related tests.

Closes https://github.com/scikit-hep/scikit-hep/issues/88.

### CODE REVIEW

**Review by marinang — APPROVED** [review]
@eduardo-rodrigues everything seems fine, thanks :)

**Comment by eduardo-rodrigues** [comment]
OK @marinang, it's all good now that I removed the submodule. I will merge soon unless you raise a point ... Thanks for the quick reaction.

**Comment by marinang** [comment]
@eduardo-rodrigues I don't see the submodule `skhep.modeling` in the list of files removed.

**Comment by eduardo-rodrigues** [comment]
> @eduardo-rodrigues I don't see the submodule `skhep.modeling` in the list of files removed.

Damn, I was going to do that first and ended up removing everything related *except* the submodule :D. Well spotted. Fixed with most recent commit.

**Comment by marinang** [comment]
Perfect :)

**Comment by eduardo-rodrigues** [comment]
Thanks @marinang, it's nice to see this package getting into what we have planned a long while ago.

**Pull request merged**
