### PR TITLE
New versions of awkward, boost-histogram, hepunits, hist, histoprint, iminuit

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Preparing a new scikit-hep release. For reference, the diff is the following:
```
-awkward~=1.0.0
+awkward~=1.1.0
-boost-histogram~=0.11.0
+boost-histogram~=0.13.0
-hepunits~=2.0.0
+hepunits~=2.1.0
-hist~=2.0.0
+hist~=2.1.0
-histoprint~=1.5.0
+histoprint~=1.6.0
-iminuit~=1.4.0
+iminuit~=2.4.0
```

 @HDembinski, I did not update `iminuit`, still pinned as `iminuit~=1.4.0` but assume you would now recommend to move to version `~2.4.0`? Advance thanks.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Morning @HDembinski, can you comment in the `iminuit` version update? Advance thanks.

**Comment by HDembinski** [comment]
Yes, please update. @eduardo-rodrigues

**Comment by eduardo-rodrigues** [comment]
> Yes, please update. @eduardo-rodrigues

OK, cool, will move to 2.4.0.

**Comment by eduardo-rodrigues** [comment]
@HDembinski, here is what I get checking the latest compatible scikit-hep versions in a docker container:
```
>>> skhep.show_versions()

System:
    python: 3.8.6 (default, Sep 24 2020, 21:45:12)  [GCC 8.3.0]
executable: /usr/local/bin/python
   machine: Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.2.5

Python dependencies:
       pip: 21.0.1
setuptools: 53.0.0
     numpy: 1.20.1
     scipy: 1.6.1
    pandas: 1.2.2
matplotlib: 3.3.4

Scikit-HEP package version and dependencies:
       awkward0: 0.15.5
        awkward: 1.1.2
boost_histogram: 0.13.0
  decaylanguage: 0.10.2
       hepstats: 0.3.1
       hepunits: 2.1.0
           hist: 2.1.0
     histoprint: 1.6.0
        iminuit: 2.4.0+ROOT-v6-23-01-RF-binSampling-685-ga642cc22e3
         mplhep: 0.2.16
       particle: 0.14.0
          skhep: 2.0.0
uproot3_methods: 0.10.0
        uproot3: 3.14.4
         uproot: 4.0.4
```
Is the `iminuit` version something you meant to have via `iminuit.__version__`?

**Comment by HDembinski** [comment]
Yes, that is ok. Since I started to contribute patches also upstream in ROOT, I added the ROOT version to my version, so it is clear which version of ROOT iminuit uses. There is a rule in the accepted format for version numbers which allows such suffixes. The ROOT suffix is very long, because it refers to a development version of ROOT and not a release.

**Comment by eduardo-rodrigues** [comment]
All clear, thank you @HDembinski :-).

**Pull request merged**
