### PR TITLE
Creation of module for converters. Just a few examples for now.

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Hi everyone,
To move forward I gave the converters a first stab, and created a module with a few examples from ROOT <-> NumPy converters as provided by root_numpy. This should be enough for a discussion.
Basic usage proposed is the following:

>>> from skhep import to
>>> # TTree -> NumPy structured array
>>> myarray = to.numpy.tree2array(mytree,...)
>>> # Back to TTree
>>> mytree = to.root.array2tree(myarray,...)

To be this code is easy to read and is self-explanatory.
There are other possibilities that I also tried, including a universal way of calling the converters. But it hides a bit too much for my taste. In any case what I committed is more than enough for a kick-off.
Please comment on this PR.
Thanks,
Eduardo

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
BTW, I hardly touched the setup.py file but we now need to have something similar to what rootpy has, to be able to run tests requiring scikit-hep and root_numpy (therefore also ROOT and NumPy) on Travis.
Anyone?

**Comment by jpivarski** [comment]
I couldn't find the implementation anywhere, but how about this for interface:

```python
import skhep.to
myarray = skhep.to.numpy(mytree)
myarray = skhep.to.numpy(mydf)
myarray = skhep.to.numpy(mytf)

mytree = skhep.to.root(myarray)
mytree = skhep.to.root(mydf)
mytree = skhep.to.root(mytf)

mydf = skhep.to.pandas(myarray)
mydf = skhep.to.pandas(mytree)
mydf = skhep.to.pandas(mydf)

mytf = skhep.to.tensorflow(myarray)
mytf = skhep.to.tensorflow(mytree)
mytf = skhep.to.tensorflow(mydf)

...
```

These entry-point functions are just an API sugar for the matrix of conversions hidden deeper within skhep. Given an object of type X and wanting an object of type Y, the user has to spell out Y ("`to.something`") but the user does not have to spell out X. Each of the above functions can just call `isinstance` to figure out what X is and dispatch the appropriate converter.

**Comment by eduardo-rodrigues** [comment]
Jim, the implementation is in the er-core branch and just by the PR top menu Under "commits". So many ways to see it ... and you will see that what I wrote is pretty much what you are now writing too. We agree , good:-).

**Comment by jpivarski** [comment]
And while it's pretty safe to have functions named `numpy`, `root`, `pandas`, `tensorflow`, etc., it's dangerous to use names like these for modules. Even though they can be distinguished from their absolute-import counterparts with relative imports, some bit of code somewhere will import the wrong thing and cause a very hard-to-debug bug. The error message won't be anything like what you expect. I've hit that several times in several different libraries. The Python standard library takes some fairly basic words in its namespace; these are a minefield as well.

But reusing common module names as function names is pretty safe: you always type `.` after a module name and `(` after a function name, so the error message is immediately helpful.

**Comment by jpivarski** [comment]
No, by "implementation," I mean I can't find the code that actually does the conversion. In each of the new files, I only see imports and renaming. Is it in an external `root_numpy`?

**Comment by eduardo-rodrigues** [comment]
The main issue is that the converters are various ones for each combination (for example root_numpy has at least 2 for ROOT <-> NumPy) *and* each of those can have quite a few options. I first tried something along a function and then got immediately something really ugly.
If we go the approach of a single numpy(...), root(...) converter then these will turn into massive beasts with lots of usecase to deal with internally. At some point I'm scared that the user will have no clue what it's actually being done. Also, keep in mind that for example for ROOT there are many starting objects, not just TTrees and TChains to name 2.

**Comment by eduardo-rodrigues** [comment]
Oops, sorry for the confusion: yes for now I left root_numpy as a dependency since that is the easiest and the way I had understood everyone including Noel preferred for now. This being said, if we decide to bring root_numpy in, then the interface does not change, just some glue code Inside skhep/to. So all good.

**Comment by eduardo-rodrigues** [comment]
The root2array and array2root, for example, are the converters from root_numpy.

**Comment by jpivarski** [comment]
TTrees and TChains (which ought to be conflated into a single concept, based on whether the input filename is a glob pattern or not) are the only objects in a ROOT file that could be called "Datasets." Maybe there'd be less confusion if the `to` module was put under `skhep.dataset` and a separate `to` module is under `skhep.aggregation` for histograms and yet another under `skhep.visualization` for plots.

For some of these converters, we'll have to open up root_numpy. Perhaps we should start by forking root_numpy under the scikit-hep organization so we can feel free to add hooks. Noel? Has root_numpy reached standalone stability?

**Comment by eduardo-rodrigues** [comment]
I'll have to think more and now have to leave the laptop.
You got me confused. What kind of conversion would go under skhep.visualization? Not any of the objects converted/dealt with in root_numpy. And I'm not all sure you would like to convert a TCanvas to <what?>.

**Comment by jpivarski** [comment]
Whatever conversions among graphics that we do (like TCanvas to Vega or Matplotlib or whatever) probably wouldn't come from root_numpy.

I'm just saying that from the point of view of Datasets (`skhep.dataset.to`), there's only one functionality we'd want from root_numpy: tree2array/array2tree. Conversions of TH1Fs, if root_numpy supports it, would go under a completely different submodule, `skhep.aggregation.to`, so there wouldn't be any user confusion. This is part of turning the focus from ROOT to the basic objects of HEP.

**Comment by eduardo-rodrigues** [comment]
Let me give it a better thought ...
Others: comments and/or other proposals :-)?

**Comment by ndawe** [comment]
For interfacing ROOT with matplotlib, we can take rootpy's root2matplotlib submodule:

https://github.com/rootpy/rootpy/blob/master/rootpy/plotting/root2matplotlib.py

Also have a look at Odo: http://odo.pydata.org/en/latest/ If we added a ROOT node to their conversion graph (with root_numpy), we could open up some interesting possibilities.

rootpy also has root2hdf5 (uses root_numpy under the hood):

https://github.com/rootpy/rootpy/blob/master/rootpy/root2hdf5.py
http://www.rootpy.org/commands/root2hdf5.html

So from rootpy we can harvest root2matplotlib and root2hdf5.

**Comment by ndawe** [comment]
Regarding root_numpy, I'd prefer to keep it as a separate low-level package since it already has a community of software around it that shouldn't be forced to become dependent on all of scikit-hep. The tree conversion functions do have many options (you can pretty much do a full event and object selection on a TTree with a single tree2array call!) but the interface we present through scikit-hep doesn't need to be the same.

Aside from converting between trees and arrays, root_numpy has several other functions for filling histograms, graphs, profiles, random sampling histograms or functions, converting ROOT matrices to numpy matrices, and converting between multidimensional ROOT histograms and multidimensional numpy arrays:

http://rootpy.github.io/root_numpy/reference/index.html

These other functions could even be used where numpy is only needed as an intermediate format to facilitate speed/efficiency or to add functionality missing in ROOT. Say in the root2matplotlib interface, instead of converting ROOT histograms into python lists that are then passed to matplotlib, the interface should instead use root_numpy's hist2array and pass the numpy array to matplotlib.

**Comment by jpivarski** [comment]
I agree— root_numpy should be a standalone module. I'm getting to be of the opinion that anything that does something recognizably useful should not be contained within SciKit-HEP, but should be a soft dependency. So for instance, root_numpy's array2tree and tree2array should be accessed through skhep.dataset.to.tree(ds) and skhep.dataset.to.numpy(ds) where ds is any kind of Dataset. The SciKit-HEP function recognizes the ds it's given and calls the appropriate root_numpy function. (Or the appropriate root_pandas function, or PyTables, etc.

The conversation about histograms and visualization was about whether such a convention could be confusing, since root_numpy provides other functionality. My argument was that root_numpy's other functionality would be exposed through functions like skhep.aggregation.to.root(agg) and skhep.visualization.to.root(viz). There's no reason why root_numpy's influence be felt all in one place.

After all, the good that SciKit-HEP is doing is organizing things.

**Comment by jpivarski** [comment]
Oh, but it would be useful to have a root_numpy codebase in the scikit-hep _organisation_ that we can add hooks to. Remember the one I pointed out that would allow streaming ROOT files into another API, such as a C API?

As an early use-case, there's a group that wants to stream data from ROOT into TensorFlow, and right now they're doing it in an awkward way by converting ROOT to Numpy in big chunks. We could provide a smooth alternative.

**Comment by eduardo-rodrigues** [comment]
This PR is obsolete since long. Closing.

**Pull request closed without merging**
