### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Major bump of version to flag major update to boost-histogram 1.0.0.

### CODE REVIEW

**Review by mayou36 — APPROVED** [review]
Looks good to me

**Comment by henryiii** [comment]
What about histoprint? I think a PlottableHistogram update is coming soon there.

**Comment by eduardo-rodrigues** [comment]
> What about histoprint? I think a PlottableHistogram update is coming soon there.

Histoprint is part of the releases since a while and there is no minor version update.

**Comment by henryiii** [comment]
I'd like to see https://github.com/scikit-hep/histoprint/pull/35 included, ideally.

**Comment by eduardo-rodrigues** [comment]
> I'd like to see [scikit-hep/histoprint#35](https://github.com/scikit-hep/histoprint/pull/35) included, ideally.

That's not a problem if it gets merged soon. Otherwise it will be automatically included in this release when installed unless the version of histoprint gets bumped from 1.6 to 1.7?

**Comment by henryiii** [comment]
Due to dropping Python 2 & 3.5, it will be bumped to 1.7 or 2.0.

**Comment by eduardo-rodrigues** [comment]
> Due to dropping Python 2 & 3.5, it will be bumped to 1.7 or 2.0.

Yep, makes sense.

**Comment by henryiii** [comment]
The change between 0.13 and 1.0 was mostly dropping Python 2 support, and the last release had 0.13, so I'm also okay with just making this a minor bump (since this is already 3.6+). Numbers are cheap, so also okay with 3.0.0.

**Comment by eduardo-rodrigues** [comment]
> The change between 0.13 and 1.0 was mostly dropping Python 2 support, and the last release had 0.13, so I'm also okay with just making this a minor bump (since this is already 3.6+). Numbers are cheap, so also okay with 3.0.0.

I'm on the same page. The only reason to bump to a major is to try and be consistent now that `scikit-hep` is a metapackage (I may have failed to do so in the past, but let's' improve :-)) - update to a major version every time a "package component" does the same. Typical updates go with a minor version, so when some package goes from x.y to x.(y+1); and only do a patch version update (probably hardly ever) if there's some reason on the side of the metapackage itself. This way we have a system that can be clearly understandable, since any `scikit-hep x.y` version will be compatible with package `package a.b.c` for all `c`.

**Comment by henryiii** [comment]
That sounds like a very reasonable plan. :)

**Comment by eduardo-rodrigues** [comment]
FYI @henryiii I will merge this a bit later today unless you see something else in the pipeline. `histoprint 2.0.0` is now in.

**Comment by henryiii** [comment]
Well, boost-histogram 1.0.0 is missing typing_extensions on Python 3.6 and 3.7, but that doesn't affect scikit-hep, as something else (at least Hist, probably lots of things) include it. So don't see anything major that would be likely to be coming soon. (And boost-histogram will be updating to 1.0.1 which would be included anyway).

**Comment by henryiii** [comment]
UHI might be nice to include.

**Comment by henryiii** [comment]
Well, we can wait until it has something useful at runtime, so never mind. In the near future, it might be nice to include.

**Comment by eduardo-rodrigues** [comment]
> UHI might be nice to include.

Sure. Ping me or create a MR in the future when it makes sense to include it.

**Comment by eduardo-rodrigues** [comment]
Hi @chrisburr, I made a new release of scikit-hep 2 days ago and notice that the feedstock for the release on conda did not appear automatically, see https://github.com/conda-forge/scikit-hep-feedstock. I'm pretty sure that worked automatically last time. Do you have an idea on what isn't working and why?

**Comment by eduardo-rodrigues** [comment]
Replying to myself - conda release now out :-).

**Comment by chrisburr** [comment]
Hey, as `scikit-hep` pins the dependencies tightly the updates basically have to be done by hand as the bot's update PRs aren't currently able to change dependencies (there is an effort to automate this, but it's more complex than you would naively expect).

The procedure is:

* Run grayskull to make a new conda-recipe (online version: https://www.marcelotrevisani.com/grayskull)
* Edit the update bot's PR to contain the new `run` dependencies (example: https://github.com/conda-forge/scikit-hep-feedstock/pull/2)
* If the CI doesn't pass, likely a dependency needs to be updated on conda-forge (in this case it was `histoprint`)
* Assuming the CI now passes, merge

Would you like me to add you to the list of `scikit-hep` package maintainers on conda-forge? (beware, there will be spam notifications)

**Comment by eduardo-rodrigues** [comment]
Thanks very much for this info, @chrisburr! I understand. It would make sense to make me maintainer on this one, yes. Thanks again.

**Pull request merged**
