### PR TITLE
Dataset class

### PR DESCRIPTION
**Pull request by jpivarski**
This is an incomplete implementation without unit tests, but I'm making it a pull request so that we can discuss it as a design proposal.

There are a few ideas here: we don't have to take all of them.

## Dataset as a wrapper class

We have now considered three ways of adding functionality to existing libraries (ROOT): rootpy uses inheritance, Ostap uses monkey patching, and this proposal uses composition. Composition [is the most flexible](https://en.wikipedia.org/wiki/Composition_over_inheritance) of the three, since it gives us full control over what methods a Dataset exposes, and if someone wants an unadulterated TTree, they just say `dataset.data`. Composition can be used in conjunction with the inheritance/patching of rootpy and Ostap, by presenting a subclassed/modified TTree in `dataset.data`, wrapped in a Dataset class.

The abstract base class is `skhep.dataset.Dataset` and the two derived classes (so far) are `skhep.dataset.NumpyDataset` and `skhep.dataset.ROOTDataset`. Every Dataset must have

   * `data`: the third-party objects that actually contain all the data, such as `ROOT.TTree` and `numpy.ndarray`.
   * `provenance`: see below
   * `datashape`: see below
   * `immutable`, `mutable`: boolean properties
   * `persistent`, `transient`: boolean properties

Many datasets share functionality, such as the ability to be read from files, written to files, converted to/from Numpy (in-place and as a copy), same for ROOT, etc. When a Dataset subclass has these properties, it multiply inherits from the [mixins](https://en.wikipedia.org/wiki/Mixin) defined in `skhep.dataset.defs`. By formalizing these features as mixins, we bundle up helper functions along with the main function they each provide. For instance, if you add a `fromFiles` method (using the `FromFiles` class), you get the private helper function `_openFileNames` that deals with glob patterns, file names versus file objects, etc. in a consistent way.

The _inconvenience_ of composition is that the user either has to insert `.data` before every method call on the third-party library, or we have to wrap each one with a redirect from `dataset` to `dataset.data`. These third-party libraries have a lot of method calls. However, using a higher-order function like `skhep.dataset.numpydataset.addNumpyMethod`, we can add them in bulk. Moreover, we have the opportunity to stick in a transformation, such as picking out a column from a NumpyDataset on which to apply the Numpy function.

For instance,

    dataset.sum("one", axis=0)

is

    dataset.data["one"].sum(axis=0)

## Representation of Numpy arrays as a Dataset

A Numpy array isn't exactly what a physicist has in mind when they think of a dataset. A physicist is thinking of something more like a TTree (or SQL table, or Pandas DataFrame, ...). The Numpy module has a not-too-frequently used "record array" that does the job, but they're hard to construct and (at least in C order) are inefficient to process in memory (large stride). I much more often use a Python dictionary of 1d Numpy arrays with the same length. These can be used in the same way as record arrays:

    recarray["columnName"][1234]
    dictof1d["columnName"][1234]

by duck typing, but differ in some corner cases. One of those corner cases is the fact that root_numpy transforms record arrays to and from TTrees.

Therefore, I have NumpyDataset take either a record array or a dictionary of 1d arrays as input and perform all operations on either format transparently. When saving to a file (.npz), I have it go to a dictionary of 1d arrays because a zipped, columnar file format has all the benefits of a ROOT file (more compact, faster to load, etc.).

## Dataset provenance

I'm on the fence about this one. We could have every operation on a Dataset increment an immutable `skhep.util.provenance.Provenance` so that students can answer the question, "Which cuts were applied in this plot?" when their advisor asks. This is one of the things we can apply when we capture Numpy/ROOT method calls.

I've kept the provenance data structure simple, easy to pick apart, and read, so that ordinary physicists might actually use it (as opposed to CMSSW provenance). It could be a killer feature, something that collaborations might someday _require_ for analyses. On the other hand, it might be difficult to capture _all_ transformations (it certainly won't capture transformations when the user does something to `.data`), and maybe not being universal completely undermines its usefulness.

Thoughts?

## Datashape, a.k.a. "Schema" or "Type system"

I removed the `typesystem.py` file from the repo because a standard exists, at least in the scientific Python ecosystem, and we should be using the standard: [Datashape](http://datashape.pydata.org/overview.html).

I didn't implement any `datashape` methods, but these would examine the Numpy arrays or TTree and present that structure in Datashape's language. That way, users can examine the structure of their datasets in a unified way, and maybe understand why one dataset is not convertable into another (e.g. a TTree with nested structures and pointers has no Numpy equivalent, barring a Numpy object array).

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
OK, there is a lot to take here. I cannot do it before tomorrow. In any case, before the discussion, could you maybe remove some of the trivial things you are deleting, to make it easier? Same for talks material.
Another triviality for now: we had agreed on "utils" rather than "util", see the Manifesto. Seems better since it will be a collection of not-even-necessary-related things.

**Comment by jpivarski** [comment]
I've renamed util to utils.

Actually, I *have* removed now-obsolete code from this branch.

**Comment by eduardo-rodrigues** [comment]
OK, thanks. Will look tomorrow. Today is not the best thing to shift work to a totally different matter ;-).

**Comment by eduardo-rodrigues** [comment]
I'm still find little time to look at everything. I see where you are getting, mostly, though some examples of how the classes are meant to be used would really help.
Some of the files have essentially no doc and it's not clear how the various classes are meant to be used. Examples are the `dependencies.py` and `provenance.py` files. For the latter,, for example, there are 2 base classes with essentially the same core code. Having some doc on what they are meant for is necessary.
If you add such doc and example usage it will very much help the review - there is a lot to take here. Thanks.

**Comment by jpivarski** [comment]
Commented.

**Comment by eduardo-rodrigues** [comment]
Finally getting back to you on the core ideas!
I like the basic ideas of the Dataset object you describe, and also related concepts such as an improved provenance.
Same as you I have a mixed feeling for the .data method. Certainly we do not want to drag such calls everywhere. This being said, once the user calls .data to get the raw object, it means (s)he will be working with plain ROOT/... objects, so won't be calling much more on the dataset object itself I would assume.
To me the basic ideas exposed here, and code, are fine. I would accept this PR and build from there.
Let's just hear from the others either in this discussion or at a meeting.

**Pull request merged**
