### PR TITLE
Release of version 3.1.0

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Updates of the minor versions of several packages:
```
- awkward~=1.1.0
+ awkward~=1.2.0
- hepstats~=0.3.0
+ hepstats~=0.4.0
- hist~=2.2.0
+ hist~=2.3.0
```

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
I thought this update is enough as a stepping stone. A future one will move to mplhep 0.3 series, which drops Python 3.7.

**Comment by henryiii** [comment]
That's fine. Next minor Hist will drop Python 3.6 as well.

**Comment by eduardo-rodrigues** [comment]
OK, good to know. Then a 3.2 will be nicer, collecting more than just one package dropping the Py 3.6 support.

**Comment by eduardo-rodrigues** [comment]
Hmm, annoying that the CI is being cancelled after this MR got merged (https://github.com/scikit-hep/scikit-hep/runs/2584306703) :S! Will probably have to wait a bit to tag and release.

**Pull request merged**
