### PR TITLE
fix the build fail comming from vectors

### PR DESCRIPTION
**Pull request by marinang**
Change  `if isinstance ( other , ( float , int , long ) )` to `if isinstance ( other , ( float , int ) )` because the long type doesn't exist in python 3.
Matt

### CODE REVIEW

**Comment by marinang** [comment]
Another problem is that __div__ is python2 only, python3 uses  __truediv__ and __floordiv__.

**Comment by eduardo-rodrigues** [comment]
Hi. You may not know, we have a tiny helper module to deal with Python 2 and 3 differences in utils/py23.py. It's better to use that ...

**Comment by eduardo-rodrigues** [comment]
py23.py can of course be extended if needed.

**Comment by marinang** [comment]
Hum I just saw, that It would solve the `long` problem but not the `__div__` problem I guess.

**Comment by eduardo-rodrigues** [comment]
Ah, yes. Am not sure how the six module does that. Maybe with just `from __future__ import division` would be enough? I would have to check all this I confess.

**Comment by marinang** [comment]
When `from __future__ import division` is on in python 2 it means that you will use the `__truediv__` method when doing `a / b` and not the standard `__div__`.  Anyway what I did is to define '__truediv__' called by `__div__` and '__itruediv__'  called by `__idiv__`!

**Pull request merged**
