### PR TITLE
SkhepNumpyArrray fix of 'at' method for ufunc. Better filling of histbook histograms from NumpyDataset.

### PR DESCRIPTION
**Pull request by marinang**
Hi,

This fix is to make an easier filling of variables from a NumpyDataset into **histbook** histograms.

Indeed if you remember my [slides](https://indico.cern.ch/event/694818/contributions/2986392/attachments/1683028/2704704/pyhep-pres.pdf) at PyHEP page 10 for instance  I had to convert the variable M, SkhepNumpyArray, to a regular array because of two issues from:

- __array_finalize__

- __array_ufunc__

which are now fixed.

Additionnaly one can now do thanks to the new `keys` method in NumpyDataset.

```python
zmumu_dataset = NumpyDataset(zmumu.arrays(["px1","px2","py1","py2","M"])) 
histogram = Hist(bin("M", 50, 0, 125))
histogram.fill(**zmumu_dataset)
```

Efficiencies have been added to Transformation details in NumpyDataset selections as well.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Thanks very much for this @marinang.
Would it not make sense to extend the tests to make sure these new goodies are OK? At times tests almost serve as examples ;-).

**Comment by marinang** [comment]
@eduardo-rodrigues True. 
I can write a set of tests, however I cannot make tests implying histbook right?

Also did the coverage plugin disappeared? It was quite helpful to see which part of the code is not tested.

**Comment by eduardo-rodrigues** [comment]
Oops. Sure, better if you only do tests that are independent of histbook. Apologies for being too fast.

Strange. I did nothing to the coverage plugin. I can still find the converage tests at https://coveralls.io/github/scikit-hep/scikit-hep!

**Comment by marinang** [comment]
@eduardo-rodrigues Tests added. 

For Python 2.6, is there a strong reason to keep it?

**Comment by eduardo-rodrigues** [comment]
Re Py 2.6: there is not such a strong reason to keep it, no, though it would be good to keep it for now, in some sense. I guess we should discuss this asap among users ... Time to revive the scikit-hep-forum list!

**Comment by chrisburr** [comment]
I typed this earlier then didn't submit it:
- Can't we add histbook to the `tests_require` section of `setup.py`?
- I think Python 2.6 support should be dropped

**Comment by eduardo-rodrigues** [comment]
Yes we can. I had already added an item in there if I remember correctly.

Py 2.6: I'm also in favour for it unless somebody objects. Maybe a little email about this to our admin list would be a good idea, to avoid missing out anyone.

**Pull request merged**
